import { Inter } from "next/font/google";
import "./globals.css";
import { SkeletonTheme } from 'react-loading-skeleton'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "User List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
    <SkeletonTheme baseColor='#4b5563' highlightColor='#9ca3af'>
        
          {children}
    </SkeletonTheme>

        </body>
    </html>
  );
}
